name: Build, publish and tag docker image
on:
  push:
    branches: master
jobs:
  build_backend:
    runs-on: ubuntu-latest
    name: Build, push and tag backend
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dev-slatto/java16-docker/java16-docker
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
